import json
import argparse
import sys

def generate_python_code(material_data):
    """Generates the Python code for the PIRIS notebook."""
    
    formula = material_data.get('formula', 'Material')
    material_id = material_data.get('material_id', 'Unknown')
    unit_cell = material_data.get('unit_cell_params')
    atomic_sites = material_data.get('atomic_sites')
    sym_ops = material_data.get('symmetry_operations')

    code_template = f'''
import numpy as np
import re
import tensorflow as tf

def build_{formula.replace("-", "_")}_sample(nx=1, ny=1, nz=1):
    """
    Builds a supercell for {formula} ({material_id}) ready for PIRIS.
    Generated by Antigravity Supercell Architect.
    """
    # --- Structural Data ---
    unit_cell = {json.dumps(unit_cell, indent=8)}
    atomic_sites = {json.dumps(atomic_sites, indent=8)}
    sym_ops = {json.dumps(sym_ops, indent=8)}
    
    # --- Internal Helpers ---
    def parse_sym(sym_op):
        variables = ['x', 'y', 'z']
        token_pattern = re.compile(r'([+-]?)(\\d+(?:/\\d+)?|\\d*\\.\\d+)?([xyz])?')
        parts = sym_op.split(',')
        M = np.zeros((3, 3))
        t = np.zeros(3)
        for i, part in enumerate(parts):
            part = part.replace(" ", "")
            tokens = token_pattern.findall(part)
            for sign, number, var in tokens:
                if sign == '' and number == '' and var == '': continue
                coeff = 1.0
                if number:
                    if '/' in number:
                        num, den = number.split('/')
                        coeff = float(num) / float(den)
                    else:
                        coeff = float(number)
                if sign == '-': coeff = -coeff
                if var:
                    j = variables.index(var)
                    M[i, j] += coeff
                else:
                    t[i] += coeff
        return M, t

    # --- Lattice Setup ---
    a, b, c = unit_cell['a'], unit_cell['b'], unit_cell['c']
    alpha, beta, gamma = np.radians(unit_cell['alpha']), np.radians(unit_cell['beta']), np.radians(unit_cell['gamma'])
    
    a_vec = np.array([a, 0.0, 0.0])
    b_vec = np.array([b * np.cos(gamma), b * np.sin(gamma), 0.0])
    aux = (np.cos(alpha) - np.cos(beta) * np.cos(gamma)) / np.sin(gamma)
    c_vec = np.array([c * np.cos(beta), c * aux, c * np.sqrt(max(0, 1 - np.cos(beta)**2 - aux**2))])

    # --- Symmetry Expansion ---
    unique_sites = []
    tol = 1e-4
    for op_str in sym_ops:
        M, t_vec = parse_sym(op_str)
        for site in atomic_sites:
            orig_frac = np.array([site['x'], site['y'], site['z']])
            new_frac = np.mod(M @ orig_frac + t_vec, 1.0)
            is_duplicate = False
            for u_site in unique_sites:
                if site['element'] == u_site['element'] and np.allclose(new_frac, u_site['frac'], atol=tol):
                    is_duplicate = True
                    break
            if not is_duplicate:
                unique_sites.append({{'element': site['element'], 'frac': new_frac}})

    # --- Supercell Replication ---
    positions, elements = [], []
    for i in range(nx):
        for j in range(ny):
            for k in range(nz):
                offset = i * a_vec + j * b_vec + k * c_vec
                for site in unique_sites:
                    cart = site['frac'][0] * a_vec + site['frac'][1] * b_vec + site['frac'][2] * c_vec
                    positions.append(cart + offset)
                    elements.append(site['element'])

    positions = np.array(positions)
    elements = np.array(elements)
    num_atoms = len(positions)
    geometria = "3D" if nx > 1 or ny > 1 or nz > 1 else "planar"
    
    # TensorFlow Conversion
    sample_atoms = tf.convert_to_tensor(positions, dtype=tf.float32)
    sample_elements = tf.convert_to_tensor(elements, dtype=tf.string)

    return num_atoms, positions, elements, sample_atoms, sample_elements, geometria

# Example Usage (Commented out):
# num_atoms, positions, elements, sample_atoms, sample_elements, gen = build_{formula.replace("-", "_")}_sample(nx=2, ny=2, nz=2)
# print(f"Built {{num_atoms}} atoms for {{gen}} geometry.")
'''
    return code_template

def main():
    parser = argparse.ArgumentParser(description="PIRIS Code Generator")
    parser.add_argument("--input", required=True, help="Path to material JSON from Skill 2")
    args = parser.parse_args()

    try:
        with open(args.input, 'r') as f:
            material_data = json.load(f)
        
        python_code = generate_python_code(material_data)
        print(python_code)
        
    except Exception as e:
        print(f"Error generating code: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
